### ISSUE TITLE
windows下端口无法映射至宿主机

### ISSUE THREAD

**Issue by alexTse824** [snowdreamtech/frp#10]
本地环境为win10，直接使用frp可正常使用

docker容器开启正常：
![image](https://user-images.githubusercontent.com/42595127/101918398-4760e400-3c04-11eb-9c12-600fc6b2183d.png)

Docker启动命令：
docker run --network host --restart always -d -v E:\frps.ini:/etc/frp/frps.ini --name frps snowdreamtech/frps

但是宿主机无法获取容器端口映射，7500管理界面端口无法访问。
求助是什么原因造成的，猜测可能和windows防火墙有关？

**Comment by snowdream** [comment]
建议先关闭防火墙试试，看看是否是防火墙的原因。

后续，可以配置防火墙规则，放行。
