### ISSUE TITLE
frps 怎么打开vhostHTTPSPort ？

### ISSUE THREAD

**Issue by Matthew-Harris-36** [snowdreamtech/frp#122]
我发现有好多和 frp 官网推荐的配置不同。请问下是版本不统一吗？

有人也遇到类似[问题](https://github.com/fatedier/frp/issues/4551)

比如监听 http 端口，官方推荐 vhostHTTPPort 就不行，得用 vhost_http_port 。

**Comment by snowdream** [comment]
https://github.com/fatedier/frp/tree/dev/conf

这里有最全的配置。

**Comment by Matthew-Harris-36** [comment]
暂时不清楚什么原因， frps 不用 Docker 按官方的部署，现在没问题了。
