### ISSUE TITLE
Ubuntu 21.04每次开机启动，frpc都工作不正常，需要手动重启下container才能正常

### ISSUE THREAD

**Issue by maondun** [snowdreamtech/frp#14]
Ubuntu 21.04每次开机启动，frpc都工作不正常，需要手动重启下container才能正常
日志如下：
2021/04/29 13:26:54 [E] [control.go:158] [b3a619eb500415cc] work connection closed before response StartWorkConn message: EOF
2021/04/29 13:26:54 [E] [control.go:158] [b3a619eb500415cc] work connection closed before response StartWorkConn message: EOF
2021/04/29 13:26:54 [E] [control.go:158] [b3a619eb500415cc] work connection closed before response StartWorkConn message: EOF
2021/04/29 13:26:54 [E] [control.go:158] [b3a619eb500415cc] work connection closed before response StartWorkConn message: EOF
2021/04/29 13:26:54 [E] [control.go:158] [b3a619eb500415cc] work connection closed before response StartWorkConn message: EOF
2021/04/29 13:34:43 [W] [service.go:104] login to server failed: lookup **xxxxxx.com on 127.0.0.53:53**: server misbehaving

感觉是因为黑体部分，开机后网络还没有ready，所以把域名（域名由于隐私改成xxxx.com了）解析到127.0.0.53了，然后就连不上服务器，但又不会自动去retry。
怎么优雅地解决这个问题呢？而不是每次都需要手动重启一下。

**Comment by snowdream** [comment]
frp 应该会自动重试的

**Comment by maondun** [comment]
> frp 应该会自动重试的

但事实上没有，碰到很多次才来反馈的。请教下怎么定位为啥不重启？或者怎么让它连不上自动重启？

**Comment by snowdream** [comment]
去 docker 里面看看 frpc 进程还在不在？

只要保证 frpc 进程在，一般会自动重试。

这里只是对 frp 进行 Docker 封装。

**Comment by maondun** [comment]
> 去 docker 里面看看 frpc 进程还在不在？
> 
> 只要保证 frpc 进程在，一般会自动重试。
> 
> 这里只是对 frp 进行 Docker 封装。
> 
> 原项目在这里：
> https://github.com/fatedier/frp

明白。frpc进程应该还在，不确定，我下次留意一下。另外，如果frpc进程不在的话，整个container不是应该会自动重启嘛，因为设置了--restart=always。
我看要不要去原项目提个issue。。。

**Comment by snowdream** [comment]
> > 去 docker 里面看看 frpc 进程还在不在？
> > 只要保证 frpc 进程在，一般会自动重试。
> > 这里只是对 frp 进行 Docker 封装。
> > 原项目在这里：
> > https://github.com/fatedier/frp
> 
> 明白。frpc进程应该还在，不确定，我下次留意一下。另外，如果frpc进程不在的话，整个container不是应该会自动重启嘛，因为设置了--restart=always。
> 我看要不要去原项目提个issue。。。

嗯，具体问题具体分析。

**Comment by maondun** [comment]
谢谢。
