### ISSUE TITLE
添加tzdate时区选项

### ISSUE THREAD

**Issue by Latezly** [snowdreamtech/frp#15]
alpine镜像没有调整时区的选项，得手动安装tzdate包之后更改，否则他只能显示UTC时区，也就是会比北京时区慢8个小时；通常在docker日志里会需要用到

如果您这边觉得需要添加的话可以看看这个commit https://github.com/Latezly/frp-docker/commit/949c53b1525f2a75043bc4b03e1d05b799188db6 我可以直接提交pr

不过我这边因为设备原因只能测试到x86_64的版本是正常的

**Comment by snowdream** [comment]
欢迎提交 PR。

**Comment by snowdream** [comment]
不建议修改。

一般使用 UTC+0时间，国际通用。

如果固定在 GMT+8,其他的地方就不适合看了。

https://www.itcoder.tech/posts/docker-timezone-localtime/

**Comment by Cp0204** [comment]
同样遇到，我是在WEBUI看连接时间有时差。

这个办法可以：

当宿主机为 Linux 系统时，我们可以直接将宿主机上的/etc/timezone和/etc/localtime挂载到容器中，这样可以保持容器和宿主机时区和时间一致。

` -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro`
