### ISSUE TITLE
如何设置计划重启

### ISSUE THREAD

**Issue by liiloo100** [snowdreamtech/frp#16]
/etc/crontabs # cat root
# do daily/weekly/monthly maintenance
# min	hour	day	month	weekday	command
*/15	*	*	*	*	run-parts /etc/periodic/15min
0	*	*	*	*	run-parts /etc/periodic/hourly
0	2	*	*	*	run-parts /etc/periodic/daily
0	3	*	*	6	run-parts /etc/periodic/weekly
0	5	1	*	*	run-parts /etc/periodic/monthly
0	4	*	*	*	/sbin/reboot >/dev/null 2>&1 这是设置重启但没有执行
这个应该怎么设置呢

**Comment by snowdream** [comment]
为什么要重启 docker 容器？

**Comment by liiloo100** [comment]
可以启动也可以不启动，我在尝试的时候计划没有被执行，不知道是什么原因，是没有这个功能还是什么呢

**Comment by snowdream** [comment]
一般是让Docker容器保持运行。

如果要定时启动停止frp，你可以使用官方的frp，加上定时任务。


发自我的iPhone
