### ISSUE TITLE
容器启动出错

### ISSUE THREAD

**Issue by iroyway** [snowdreamtech/frp#17]
运行 后出现下面错误
![image](https://user-images.githubusercontent.com/51533547/126259064-0a7e206f-38b8-477d-b4df-9e4d1ff1f241.png)
google搜索后发现/etc/frp目录下面的frps.ini是创建的一个文件夹，于是删除了frps.ini这个文件夹，重新新建了文件名为frps.ini的文件，再停止删除容器后，容器启动不起来。
在去查看/var/lib/docker/overlay2/xxx目录/merged" 发现merged目录不存在，这是什么原因呢？请大佬帮忙看下。
使用的系统是 Debian 4.9.272-1 (2021-06-21) x86_64 GNU/Linux

**Comment by snowdream** [comment]
需要在宿主机内创建frps.ini文件，不是文件夹，然后挂载到容器内去。
