### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cxbaba123** [snowdreamtech/frp#21]
![image](https://user-images.githubusercontent.com/94046670/164957444-d08c38c6-67a0-40b0-9ce1-86293387ad70.png)
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/etc/frp/frps.ini" to rootfs at "/etc/frp/frps.ini" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

**Comment by snowdream** [comment]
you should create the dir /etc/frp/ and touch the file /etc/frp/frps.ini yourself.

https://github.com/fatedier/frp

**Comment by Minidoracat** [comment]
我有提前建立文件，卻也出現這個問題
後來發現是docker版本問題，重新安裝docker到最新版(目前20.10.16)就沒有這問題了
