### ISSUE TITLE
威联通创建frpc时不成功

### ISSUE THREAD

**Issue by yxp0621** [snowdreamtech/frp#22]
![image](https://user-images.githubusercontent.com/104353590/170613947-52a8bfcc-f078-4917-849a-7eb4c8c090b6.png)

open ./frpc.ini: no such file or directory

**Comment by snowdream** [comment]
frpc.ini需要自己配置，并挂载到容器内部。

**Comment by yxp0621** [comment]
我是跟frps一样创建了frpc.ini文件，并挂载在了etc/frp文件夹。Frps这么操作是正常的，frpc就出现这个提示

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年5月29日 22:30
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [snowdreamtech/frp] 威联通创建frpc时不成功 (Issue #22)


frpc.ini需要自己配置，并挂载到容器内部。

―

**Comment by yxp0621** [comment]
我是跟frps一样创建了frpc.ini文件，并挂载在了etc/frp文件夹。Frps这么操作是正常的，frpc就出现这个提示
