### ISSUE TITLE
如何将本地的多个web内网穿透到云服务器上的frps

### ISSUE THREAD

**Issue by m986883511** [snowdreamtech/frp#24]
云服务器上的设置

# frps.ini
[common]
bind_port = 7000
vhost_http_port = 8080

本地web1
# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[web]
type = http
local_port = 80
custom_domains = 23.23.23.23

本地另外一台机器上web2，这里怎么设置呢？
# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[web]
type = http
local_port = 80
custom_domains = 23.23.23.23

**Comment by snowdream** [comment]
nginx？

**Comment by heyzqq** [comment]
之前过研究过，后来还是放弃了，就是用楼上说的 Nginx 比较方便。

多个 web 配置多个域名好像可以，还有个子域名 subdomain 可以配置，但是能不能都是 80 端口就不知道了（试一下，如果不行那就不好玩了）

**Comment by zctmdc** [comment]
```ini
[http_xx_sub]
type = http
subdomain = xx
local_ip = 127.0.0.1
local_port = 8080

[http_xy_sub]
type = http
subdomain = xy
local_ip = 192.168.1.100
local_port = 8081

[http_xx_cus]
type = http
custom_domains = xx.example.org
local_ip = 127.0.0.1
local_port = 8080

[http_xy_cus]
type = http
custom_domains = xy.example.org
local_ip = 127.0.0.1
local_port = 8081
```
