### ISSUE TITLE
容器连接上后，过段时间面板显示wait

### ISSUE THREAD

**Issue by Amolindex** [snowdreamtech/frp#26]
如题，服务器是下载文件自行配置的，另一台主机连接服务器并没有问题，在这台主机上因为不方便设置开机自启，使用了docker来配置frpc，但是过一段时间就会断开连接，进入面板发现状态提醒为wait start。

**Comment by Amolindex** [comment]
如题，服务器是下载文件自行配置的，另一台主机连接服务器并没有问题，在这台主机上因为不方便设置开机自启，使用了docker来配置frpc，但是过一段时间就会断开连接，进入面板发现状态提醒为wait start。

**Comment by snowdream** [comment]
建议查询一下相关日志
