### ISSUE TITLE
经反复测试发现，最新版`0.47.0`经常出现`502页面`，非常不稳定

### ISSUE THREAD

**Issue by Juway111** [snowdreamtech/frp#28]
<font color=red size=4>==2023.03.05更新：经反复测试发现，最新版`0.47.0`经常出现`502页面`，非常不稳定，frp一定要力求稳定，不需要太多花哨的功能，现在退回`0.46.1`版养老。==</font>。虽然我不知道啥原因。确实存在这样的问题。

**Comment by snowdream** [comment]
请前往官方项目反馈问题，https://github.com/fatedier/frp

这里只是非官方打包 Docker。
