### ISSUE TITLE
升级到v0.52.1后，连接不上frps

### ISSUE THREAD

**Issue by netfun2000** [snowdreamtech/frp#34]
frps是运行在win2003server上的一个老版本，至少v0.52.1之前运行正常，昨晚升级后，今天不能用了。

**Comment by penndu** [comment]
frp新版修改了配置文件，之前是frps.ini，现在是frps.toml。
需要配置新的配置文件才可。
https://github.com/fatedier/frp/blob/dev/conf/frps.toml
