### ISSUE TITLE
docker frpc container launch param error

### ISSUE THREAD

**Issue by koujiangheng** [snowdreamtech/frp#36]
The docker launch cmd is ```docker run --restart=always --network host -d -v /etc/frp/frpc.ini:/etc/frp/frpc.ini --name frpc snowdreamtech/frpc```
however, the args in container is "/usr/bin/frpc -c /etc/frp/frpc.toml", this will cause container always restarting.
please fix it.
```[
    {
        "Id": "f2156d815a9a1c59e1445177ba071eccb2915ef76a3b78bbc238328747ba9d6e",
        "Created": "2023-10-18T08:39:19.240268069Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "/usr/bin/frpc -c /etc/frp/frpc.toml"
        ],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-10-18T08:40:11.985570198Z",
            "FinishedAt": "2023-10-18T08:40:12.039484257Z"
        },```

**Comment by snowdream** [comment]
[v0.52.0](https://github.com/fatedier/frp/releases/tag/v0.52.0)
Features
Configuration: We now support` TOML, YAML, and JSON` for configuration. Please note that`INI `is deprecated and will be removed in future releases. New features will only be available in TOML, YAML, or JSON. Users wanting these new features should switch their configuration format accordingly. https://github.com/fatedier/frp/issues/2521
Breaking Changes
Change the way to start the visitor through the command line from frpc stcp --role=visitor xxx to frpc stcp visitor xxx.
Modified the semantics of the server_addr in the command line, no longer including the port. Added the server_port parameter to configure the port.
No longer support range ports mapping in TOML/YAML/JSON.

**Comment by snowdream** [comment]
[v0.52.0](https://github.com/fatedier/frp/releases/tag/v0.52.0)
Features
Configuration: We now support` TOML, YAML, and JSON` for configuration. Please note that`INI `is deprecated and will be removed in future releases. New features will only be available in TOML, YAML, or JSON. Users wanting these new features should switch their configuration format accordingly. https://github.com/fatedier/frp/issues/2521
Breaking Changes
Change the way to start the visitor through the command line from frpc stcp --role=visitor xxx to frpc stcp visitor xxx.
Modified the semantics of the server_addr in the command line, no longer including the port. Added the server_port parameter to configure the port.
No longer support range ports mapping in TOML/YAML/JSON.
