### ISSUE TITLE
无法启动多docker 客户端

### ISSUE THREAD

**Issue by kpeng2016** [snowdreamtech/frp#4]
我在启动一个docker 服务之后，另外有两个服务器中各自启动了客户端的docker,但是似乎只能有一个能远程访问，另一个一直提示“The page you visit not found.”, 反正就是哪个先启动，就哪个能够访问有效。这个是什么道理呢？
谢谢！

**Comment by snowdream** [comment]
端口冲突？

**Comment by kpeng2016** [comment]
> 端口冲突？

请问，你说的端口冲突是什么意思？是说两个子的不能有相同的端口？还是？
请指教，谢谢！

**Comment by snowdream** [comment]
> > 端口冲突？
> 
> 请问，你说的端口冲突是什么意思？是说两个子的不能有相同的端口？还是？
> 请指教，谢谢！

你可以贴一下配置文件，隐去重要信息。
