### ISSUE TITLE
docker 部署完成之后端口不显示

### ISSUE THREAD

**Issue by John4d3** [snowdreamtech/frp#43]
防火墙已经关闭，请问是什么原因呢？谢谢

**Comment by snowdream** [comment]
最近版本的配置文件不支持 ini 格式，可以是 toml 格式。

是否是这个原因？

**Comment by John4d3** [comment]
> 最近版本的配置文件不支持 ini 格式，可以是 toml 格式。
> 
> 是否是这个原因？

原来如此！问题解决了，谢谢解答。
