### ISSUE TITLE
请问snowdreamtech/frpc的配置语法有吗？现在网上教程五花八门，容器竟然不能识别type = http

### ISSUE THREAD

**Issue by chinesecalvin8282** [snowdreamtech/frp#46]
请问snowdreamtech/frpc的配置语法有吗？当使用type = http的时候，容器无法成功运行。使用 type = tcp则OK，但加上plugin相关参数时，也常常导致运行出错。

Is there any configuration syntax for snowdreamtech/frpc? When using type=http, the container cannot run successfully. Using type=TCP is OK, but adding plugin related parameters often leads to runtime errors.

**Comment by snowdream** [comment]
https://gofrp.org/zh-cn/
