### ISSUE TITLE
2024-03-26 07:01:32.262 [W] [client/service.go:297] connect to server error: dial tcp 127.0.0.1:7000: connect: connection refused

### ISSUE THREAD

**Issue by chenxudong2020** [snowdreamtech/frp#47]
[common]
server_addr = XXXX
server_port = 7000
tls_enable = false
user = YYYYYYYYYYYYYYYYYYY
token = ZZZZZZZZ

[derpertcp]
type = tcp
local_ip = 127.0.0.1
local_port = 443
remote_port = 44300
 
[derperudp]
type = udp
local_ip = 127.0.0.1
local_port = 3478
remote_port = 34780
上面的内容是frpc.ini的内容
使用如下命令创建docker
docker run  --network host -d -v /etc/frp/frpc.ini:/etc/frp/frpc.ini --name frpc snowdreamtech/frpc

启动报connect to server error: dial tcp 127.0.0.1:7000: connect: connection refused
其中server_addr user token 为了保密用 X Y Z等字符替换

**Comment by snowdream** [comment]
FRP 官方文档：https://gofrp.org/zh-cn/docs/
FRP 官方问题讨论区： https://github.com/fatedier/frp/issues

根据官方信息，从frp 0.52.0开始，ini格式被废弃，改为toml,json,yaml。
请按照提示，将配置文件升级成toml格式。
https://github.com/fatedier/frp#configuration-files
[Full configuration file for frps (Server)](https://github.com/fatedier/frp/blob/dev/conf/frps.toml)
[Full configuration file for frpc (Client)](https://github.com/fatedier/frp/blob/dev/conf/frpc.toml)
