### ISSUE TITLE
创建镜像报错

### ISSUE THREAD

**Issue by keatonLiu** [snowdreamtech/frp#49]
```shell
docker run --restart=always --network host -d -v /etc/frp/frps.toml:/etc/frp/frps.toml --name frps snowdreamtech/frps
```

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/frp/frps.toml" to rootfs at "/etc/frp/frps.toml": mount /etc/frp/frps.toml:/etc/frp/frps.toml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

**Comment by keatonLiu** [comment]
运行这个命令之后他创建了个frps.toml的文件夹
这个不应该是个文件才对嘛？

**Comment by snowdream** [comment]
配置文件需要自己创建，请参考置顶问题。
