### ISSUE TITLE
求助大神：找不到frpc, 找不到frpc.ini

### ISSUE THREAD

**Issue by kanchixp** [snowdreamtech/frp#5]
大神你好，我的NAS是QNAP 212P3，应该是ARM64的机器，最近折腾了好几天frpc，但就是不成功，要么就是找不到frpc，要么就是找不到frpc.ini，也曾尝试直接用winscp将frpc复制到/usr/bin，将frpc.ini复制到/etc/frp，但始终不能成功启动。能否指导一下正确的安装方法？包括如何映射正确的共享文件夹？非常感谢！！！
![40360A04-23AB-413D-A71A-9778CC777059](https://user-images.githubusercontent.com/57894256/69040095-2c836680-0a28-11ea-8140-2bd8ed5de5f0.png)
![33EC32EE-AD23-41F3-A3F7-7DC5DCD5F507](https://user-images.githubusercontent.com/57894256/69040096-2c836680-0a28-11ea-893e-45b4a0dc72e8.png)
![82011E85-882F-48BC-8F54-101A22AB2D3F](https://user-images.githubusercontent.com/57894256/69040099-2d1bfd00-0a28-11ea-9b20-859c86e6a3ce.png)

**Comment by snowdream** [comment]
frpc.ini 需要根据自己需求配置，这里有详细文档。

https://github.com/fatedier/frp/blob/master/README_zh.md


frpc封装在Docker镜像中。
docker run --restart=always --network host -d -v /etc/frp/frpc.ini:/etc/frp/frpc.ini --name frpc snowdreamtech/frpc
