### ISSUE TITLE
同样的 frpc.toml 放docker里就运行不了

### ISSUE THREAD

**Issue by icaca** [snowdreamtech/frp#50]
每次都请求127.0.0.1 然后docker cp出来文件没有问题

**Comment by icaca** [comment]
frpc:
    container_name: frpc
    image: snowdreamtech/frpc
    restart: always
    volumes:
      - /mnt/nvme1/common/frp/frpc.toml:/etc/frp/frpc.toml
    environment:
      - TZ=Asia/Shanghai
    network_mode: "host"



frpc.toml
serverAddr = "xxxxxxxxxxxxx"
serverPort = 7001

[[proxies]]
name = "pal1"
type = "udp"
localIP = "127.0.0.1"
localPort = 8211
remotePort = 8211

[[proxies]]
name = "pal2"
type = "udp"
localIP = "127.0.0.1"
localPort = 27015
remotePort = 27015

**Comment by icaca** [comment]
我把 serverPort 改了几次，发现docker 都会请求7000，因此我觉得程序并没有访问 /etc/frp/frpc.toml

但是我看dockerfile，确实用的 ENTRYPOINT /usr/bin/frpc -c /etc/frp/frpc.toml
就不知道问题在哪了

**Comment by icaca** [comment]
docker compose 指定版本貌似可以了。
snowdreamtech/frpc:0.57.0

**Comment by snowdream** [comment]
注意检查docker镜像版本。有些镜像网站，会拉取旧版本的docker镜像。
使用tag拉取，可以运行，说明latest拉取回来的，是旧的镜像。
你可以检查一下。
