### ISSUE TITLE
大神请看一下这是什么问题？谢谢！

### ISSUE THREAD

**Issue by williamx41** [snowdreamtech/frp#8]
![frpc](https://user-images.githubusercontent.com/62884960/77909231-973e8b80-72bf-11ea-8baa-88b5f7e84fee.jpg)
大神请看一下这是什么问题？完全看不懂，谢谢！

**Comment by snowdream** [comment]
-v /etc/frp/frpc.ini:/etc/frp/frpc.ini

前半部分这个配置文件，需要自己配置。
自定义配置请注意路径。
配置请参考：https://github.com/fatedier/frp

/etc/frp/frpc.ini
